PDR-35 api github actions workflows

diff --git a/.github/workflows/deploy-api-prod.yaml b/.github/workflows/deploy-api-prod.yaml
--- a/.github/workflows/deploy-api-prod.yaml
+++ b/.github/workflows/deploy-api-prod.yaml
@@ -1,12 +1,13 @@
-name: Deploy PDR-API Dev
+name: Deploy PDR-API Prod
 
-run-name: Deploying ${{ github.ref_name }} (API) to dev
+run-name: Deploying ${{ github.ref_name }} (API) to prod
 
 on:
-  push:
-    branches: [main]
-    paths: "pdr-api/**"
   workflow_dispatch:
+  inputs:
+    releaseTag:
+      description: "Tag of version to be promoted to prod"
+      required: true
 
 env:
   AWS_REGION: "ca-central-1"
@@ -18,12 +19,20 @@ permissions:
 jobs:
   deploy-api:
     runs-on: ubuntu-latest
-    environment: dev
+    environment: prod
     steps:
       ### Checkout GitHub Repo
       - name: Checkout repo
-        uses:
-          actions/checkout@v3
+        uses: actions/checkout@v3
+        with: 
+          ref: ${{ github.events.inputs.releaseTag }}
+
+      ### Tag not found
+      - name: Tag not found
+        if: ${{ failure() }}
+        run: |
+          echo "::error::Git Tag not found, please double check input"
+          exit 1
 
       ### Setup AWS SAM
       - name: Setup AWS SAM
diff --git a/.github/workflows/deploy-api-test.yaml b/.github/workflows/deploy-api-test.yaml
--- a/.github/workflows/deploy-api-test.yaml
+++ b/.github/workflows/deploy-api-test.yaml
@@ -1,12 +1,11 @@
-name: Deploy PDR-API Dev
+name: Deploy PDR-API Test
 
-run-name: Deploying ${{ github.ref_name }} (API) to dev
+run-name: Deploying ${{ github.ref_name }} (API) to test
 
 on:
   push:
-    branches: [main]
-    paths: "pdr-api/**"
-  workflow_dispatch:
+    tags:
+      - "*"
 
 env:
   AWS_REGION: "ca-central-1"
@@ -18,12 +17,21 @@ permissions:
 jobs:
   deploy-api:
     runs-on: ubuntu-latest
-    environment: dev
+    environment: test
     steps:
       ### Checkout GitHub Repo
       - name: Checkout repo
         uses:
           actions/checkout@v3
+        with: 
+          ref: ${{ github.ref_name }}
+
+      ### Tag not found
+      - name: Tag not found
+        if: ${{ failure() }}
+        run: |
+          echo "::error::Git Tag not found, please double check input"
+          exit 1
 
       ### Setup AWS SAM
       - name: Setup AWS SAM
